services:

  app:
    container_name: auth-app-server
    build: .
    command: ./main
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: auth-postgres-server
    image: postgres:alpine
    ports:
      - "5430:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres "]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    